
# This file is sourced by the default ~/.bashrc file. It is a dedicated space
# for users to add their custom Bash configurations, aliases, functions, and
# environment variables.
# If you wish to override the behavior of "cd" with no argument to point to
# your default workspace folder, uncomment the following function:
# cd() {
#     if [[ -z "$1" || "$1" == "--" ]]; then
#         builtin cd "$DEFAULT_WORKSPACE" || return
#     else
#         builtin cd "$@"
#     fi
# }

# --- Persistent user-space installs (survive container recreate) ---
# $BEACON_USER_DIR/.local lives on NFS, unlike $HOME. PYTHONUSERBASE already
# points here (set by the platform), so `pip install --user` binaries land
# here too; this just puts them on PATH.
#
# Guards on PATH additions: this file is sourced up to three times per shell
# in the normal IDE+tmux setup — once by code-server's env resolution (bash -l
# at startup), once by the terminal's shellIntegration init-file, and once by
# the tmux login shell. Without guards each pass prepends a duplicate set.
# See notes/workstation/container-durability.md for the full trace.

# Point other package managers' install/global dirs here as well, instead of
# their defaults under $HOME (ephemeral) or /usr (not writable). These are
# env vars, not on-disk config, because dotfiles like ~/.npmrc don't survive
# a container recreate either.
export NPM_CONFIG_PREFIX="$BEACON_USER_DIR/.local"
export GOPATH="$BEACON_USER_DIR/.local/go"
export GOBIN="$BEACON_USER_DIR/.local/bin"
export CARGO_HOME="$BEACON_USER_DIR/.local/cargo"

[[ ":$PATH:" != *":$BEACON_USER_DIR/.local/bin:"* ]] && export PATH="$BEACON_USER_DIR/.local/bin:$PATH"
# ~/.local/bin (where the `claude` symlink lives) is normally only added to
# PATH by ~/.profile, which only runs for login shells. This file is sourced
# unconditionally from ~/.bashrc, so add it here too — otherwise plain
# non-login shells (e.g. a bare `bash`, some tmux pane configs) won't see it.
[[ ":$PATH:" != *":$HOME/.local/bin:"* ]] && export PATH="$HOME/.local/bin:$PATH"
[[ ":$PATH:" != *":$CARGO_HOME/bin:"* ]] && export PATH="$CARGO_HOME/bin:$PATH"

# --- XDG config dir (survives container recreate) ---
# ~/.config is on the ephemeral container root fs. XDG_CONFIG_HOME redirects
# any XDG-compliant tool's config (fish's config.fish/functions/completions/
# conf.d, among others) to NFS. fish's *data* (history, universal variables
# via `set -U`) and *cache* already land on NFS today without this — the
# platform sets XDG_DATA_HOME/XDG_CACHE_HOME globally to paths under
# .beaconide/{data,cache} — this just covers the third, previously-unset XDG
# dir (config). See notes/workstation/container-durability.md.
#
# Fixed 2026-08-11: install.sh's fish_rc()/git_rc() now resolve
# $XDG_CONFIG_HOME themselves (falling back to the old hardcoded paths when
# it's unset, so other machines this repo installs to are unaffected) —
# dotfiles-managed fish/git config lands here instead of on ephemeral $HOME.
# See notes/workstation/container-durability.md.
export XDG_CONFIG_HOME="$BEACON_USER_DIR/.config"

# --- Claude Code config (survives container recreate) ---
# ~/.claude is on the ephemeral container root fs. CLAUDE_CONFIG_DIR redirects
# all of Claude Code's state (settings, transcripts, credentials, memory) to
# NFS. Credentials on Linux are stored in this directory (not the system
# keychain), so they persist across recreates too — no re-login needed.
export CLAUDE_CONFIG_DIR="$BEACON_USER_DIR/.claude"

# --- clauder (survives container recreate) ---
# clauder keeps its own durable storage under $CLAUDER_USER_HOME/.clauder --
# the promoted artifact venvs PATH points at, refs/, state.json, promoted.json.
# $HOME is regenerated every boot, so without this the install and the runtime
# disagree about where that directory is and the tree splits in two.
export CLAUDER_USER_HOME="$BEACON_USER_DIR"
# `clauder install` splices its `claude` shell function into ~/.bashrc, which
# the platform regenerates on every boot. Point it at this file -- the durable
# one ~/.bashrc sources -- so the function survives a recreate.
export DOTFILES_BASH_RC="$DEFAULT_WORKSPACE/.bashrc"

# --- GitHub SSH auth (survives container recreate) ---
# ~/.ssh is on the ephemeral container root fs and gets wiped/regenerated by
# the platform every boot (it's re-populated with internal deploy keys only,
# e.g. id_wst_git_wst_master_ro_rsa), so both our GitHub key and its
# known_hosts entry live on NFS instead.
#
# Nothing is exported here, deliberately. This used to set GIT_SSH_COMMAND at
# both the key and known_hosts, but that variable is global: it forced
# IdentitiesOnly with the personal key at *every* host, git.wsq.io included,
# and took precedence over ~/.ssh/config for anything invoked through git — so
# raw `ssh` and `git` disagreed about which key to offer. The identity is
# scoped per-host in ~/.ssh/config instead, which inigo/setup/bootstrap.sh
# rewrites on each fresh container (it is the ephemeral half of this pair).
# See the 260818 ssh investigation under inigo/dev/stacks/.


# --- one-time provisioning for a fresh container ---
# bootstrap.sh installs what a container recreate wipes: tmux config (tmux
# ignores XDG_CONFIG_HOME, so unlike everything else here it has no durable
# target to be pointed at), and the git include that keeps Beacon's global
# pre-commit hook out of personal repos. It used to be run by hand, which meant
# it was forgotten and sessions silently ran on stock tmux defaults.
#
# $HOME being wiped is itself the "fresh container" signal, so the marker lives
# there. mkdir is atomic: with several tmux panes starting at once exactly one
# claims it and the rest skip -- and this file being sourced up to three times
# per shell (see the PATH note above) costs nothing after the first.
#
# Run as a child process, never sourced: bootstrap.sh sets `set -euo pipefail`,
# which would kill the shell on any failure. The failure branch only reports --
# a broken bootstrap must never stand between you and a prompt.
if mkdir "$HOME/.bootstrapped" 2>/dev/null; then
    "$DEFAULT_WORKSPACE/inigo/setup/bootstrap.sh" \
        || echo "NOTE: bootstrap.sh failed -- rerun by hand after 'rmdir ~/.bootstrapped'"
fi



# <<< clauder >>>
[ -f "/mnt/home0/wst/workspaces/Inigo.HidalgoRey.axpo.com/.clauder/shell/init.bash" ] && source "/mnt/home0/wst/workspaces/Inigo.HidalgoRey.axpo.com/.clauder/shell/init.bash"
# <<< /clauder >>>

# <<< dotfiles >>>
export DOTFILE_DIR="/mnt/home0/wst/workspaces/Inigo.HidalgoRey.axpo.com/default/inigo/dev/repos/ihr/.dotfiles/sh"
source "$DOTFILE_DIR/functions.sh"
source "$DOTFILE_DIR/fish.sh"
# <<< /dotfiles >>>
